version: '3.8'

services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --reload
    ports:
      - "5001:5000"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_ENV=development